### Вычисления с помощью Numpy

#### Задание 1

In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3, 3, 1],
              [6, 8, 11, 10, 7]])
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [8]:
a = a.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [22]:
mean_a = a.mean(axis=0)
print('Среднее значение по каждому признаку:') 
print(', '.join(map(str, mean_a)))

Среднее значение по каждому признаку:
2.0, 8.4


#### Задание 2

In [24]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Задание 3

In [39]:
# транспонируем a_centered
a_centered_t = a_centered.T
# и найдём скалярное произведение столбцов
a_centered_sp = np.dot(a_centered_t[0], a_centered_t[1])
print(f'Скалярное произведение столбцов: a_centered_sp = {a_centered_sp}')

Скалярное произведение столбцов: a_centered_sp = 8.0


In [40]:
# N - число наблюдений, равное 5
# N - 1 = 4
a_centered_sp / 4

2.0

#### Задание 4

In [43]:
# выполним проверку, используя другой алгоритм расчёта ковариации
np.cov(a.T)[0, 1] == a_centered_sp / 4

True