### Задания на повторение материала

In [1]:
import numpy as np

#### Задание 1

In [5]:
a = np.arange(12, 24, 1)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### Задание 2

In [13]:
a1 = a.reshape(6, 2)
a2 = a.reshape(3, 4)
a3 = a.reshape(2, 6)
a4 = a.reshape(4, 3)
a5 = a.reshape(4, 3, order='F')

#### Задание 3

In [22]:
a1 = a.reshape(-1, 2)
a2 = a.reshape(-1, 3)
a3 = a.reshape(2, -1)
a4 = a.reshape(3, -1)
a5 = a.reshape(3, -1, order='F')

#### Задание 4

In [26]:
b = np.array([[12], [13], [14], [15], [16], [17], [18], [19], [20], [21], [22], [23]])
b1 = b.T
b, b1
# такой массив можно назвать одномерным только формально. Егот в том числе можно транспонировать.
# истинно одномерный массив, например, 'a' транспонировать методом numpy не получается.
# работа с одномерными и двумерными массивами в данном примере различается

(array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]),
 array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]]))

#### Задание 5

In [33]:
c = np.random.randn(3, 4)
print(f'Размерность оригинального двумерного массива: {c.size}')
c = c.flatten()
print(f'Размерность оодномерного массива: {c.size}')

Размерность оригинального двумерного массива: 12
Размерность оодномерного массива: 12


#### Задание 6

In [40]:
a = np.arange(20, 0, -2, dtype=int)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### Задание 7

In [45]:
b = np.arange(20, 1, -2, dtype=int)
b
# не вижу разницы
# либо задание с подвохом, а во втором случае по условию подразумевается двумерный массив 

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### Задание 8

In [53]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
print(v)
print(f'Size: {v.size}')

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Size: 10


#### Задание 9

In [59]:
a = np.arange(12)
A = a.reshape(4, 3)
At = A.T
A, At

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]]))

In [61]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

#### Задание 10

In [63]:
np.random.seed(42)

#### Задание 11

In [72]:
c = np.random.randint(0, 16, 16)
c

array([11, 11, 12,  8, 12, 14, 12,  0,  8,  6,  8,  7,  0, 11,  7,  7])

#### Задание 12

In [83]:
C = c.reshape(4, 4)
D = B + C * 10
# определитель
print(f'Определитель: {np.linalg.det(D)}')
# ранг
print(f'Ранг: {np.linalg.matrix_rank(D)}')
# обратная матрица
D_inv = np.linalg.inv(D)
D, D_inv
# np.dot(D, D_inv)

Определитель: 69479600.00000006
Ранг: 4


(array([[115, 124, 143, 112],
        [134, 190, 206, 122],
        [103, 146, 229, 282],
        [ 32, 232, 282, 372]]),
 array([[ 0.02744115, -0.01370589, -0.00252218, -0.00185493],
        [ 0.03778922, -0.01590366, -0.02562162,  0.01326116],
        [-0.06777759,  0.03968071,  0.02845555, -0.01417855],
        [ 0.02545179, -0.01898313, -0.0053751 ,  0.00532559]]))